// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// case_path_nonsmooth
Rcpp::List case_path_nonsmooth(arma::vec a, arma::mat B, arma::vec c, double lam, double alpha_0, double alpha_1, int j, double beta_0_w0, arma::vec beta_w0, arma::vec theta_w0);
RcppExport SEXP _Caseinflu_case_path_nonsmooth(SEXP aSEXP, SEXP BSEXP, SEXP cSEXP, SEXP lamSEXP, SEXP alpha_0SEXP, SEXP alpha_1SEXP, SEXP jSEXP, SEXP beta_0_w0SEXP, SEXP beta_w0SEXP, SEXP theta_w0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_1(alpha_1SEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< double >::type beta_0_w0(beta_0_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_w0(beta_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_w0(theta_w0SEXP);
    rcpp_result_gen = Rcpp::wrap(case_path_nonsmooth(a, B, c, lam, alpha_0, alpha_1, j, beta_0_w0, beta_w0, theta_w0));
    return rcpp_result_gen;
END_RCPP
}
// CaseInfluence_nonsmooth
Rcpp::List CaseInfluence_nonsmooth(arma::vec a, arma::mat B, arma::vec c, double lam, double alpha_0, double alpha_1, double beta_0_w0, arma::vec beta_w0, arma::vec theta_w0, std::string model_class, std::string influence_measure);
RcppExport SEXP _Caseinflu_CaseInfluence_nonsmooth(SEXP aSEXP, SEXP BSEXP, SEXP cSEXP, SEXP lamSEXP, SEXP alpha_0SEXP, SEXP alpha_1SEXP, SEXP beta_0_w0SEXP, SEXP beta_w0SEXP, SEXP theta_w0SEXP, SEXP model_classSEXP, SEXP influence_measureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_1(alpha_1SEXP);
    Rcpp::traits::input_parameter< double >::type beta_0_w0(beta_0_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_w0(beta_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_w0(theta_w0SEXP);
    Rcpp::traits::input_parameter< std::string >::type model_class(model_classSEXP);
    Rcpp::traits::input_parameter< std::string >::type influence_measure(influence_measureSEXP);
    rcpp_result_gen = Rcpp::wrap(CaseInfluence_nonsmooth(a, B, c, lam, alpha_0, alpha_1, beta_0_w0, beta_w0, theta_w0, model_class, influence_measure));
    return rcpp_result_gen;
END_RCPP
}
// LocalInfluence_nonsmooth
arma::vec LocalInfluence_nonsmooth(arma::vec a, arma::mat B, arma::vec c, double lam, double alpha_0, double alpha_1, double beta_0_w0, arma::vec beta_w0, arma::vec theta_w0, std::string model_class, std::string influence_measure);
RcppExport SEXP _Caseinflu_LocalInfluence_nonsmooth(SEXP aSEXP, SEXP BSEXP, SEXP cSEXP, SEXP lamSEXP, SEXP alpha_0SEXP, SEXP alpha_1SEXP, SEXP beta_0_w0SEXP, SEXP beta_w0SEXP, SEXP theta_w0SEXP, SEXP model_classSEXP, SEXP influence_measureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_0(alpha_0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_1(alpha_1SEXP);
    Rcpp::traits::input_parameter< double >::type beta_0_w0(beta_0_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_w0(beta_w0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_w0(theta_w0SEXP);
    Rcpp::traits::input_parameter< std::string >::type model_class(model_classSEXP);
    Rcpp::traits::input_parameter< std::string >::type influence_measure(influence_measureSEXP);
    rcpp_result_gen = Rcpp::wrap(LocalInfluence_nonsmooth(a, B, c, lam, alpha_0, alpha_1, beta_0_w0, beta_w0, theta_w0, model_class, influence_measure));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _Caseinflu_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// logistic_Newton_low_dimension
Rcpp::List logistic_Newton_low_dimension(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, int case_index, double epsilon, double L);
RcppExport SEXP _Caseinflu_logistic_Newton_low_dimension(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP case_indexSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_Newton_low_dimension(X, Y, theta_0, t_max, lam, case_index, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// logistic_Newton_high_dimension
Rcpp::List logistic_Newton_high_dimension(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, int case_index, double epsilon, double L);
RcppExport SEXP _Caseinflu_logistic_Newton_high_dimension(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP case_indexSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_Newton_high_dimension(X, Y, theta_0, t_max, lam, case_index, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// logistic_GD
Rcpp::List logistic_GD(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, int case_index, double epsilon, double L);
RcppExport SEXP _Caseinflu_logistic_GD(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP case_indexSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_GD(X, Y, theta_0, t_max, lam, case_index, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// logistic_compute_LOO
arma::vec logistic_compute_LOO(arma::mat X, arma::vec Y, arma::vec theta_init, double lam, int case_index);
RcppExport SEXP _Caseinflu_logistic_compute_LOO(SEXP XSEXP, SEXP YSEXP, SEXP theta_initSEXP, SEXP lamSEXP, SEXP case_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_compute_LOO(X, Y, theta_init, lam, case_index));
    return rcpp_result_gen;
END_RCPP
}
// CaseInfluence_logistic
Rcpp::List CaseInfluence_logistic(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, double epsilon, std::string method, std::string influence_measure);
RcppExport SEXP _Caseinflu_CaseInfluence_logistic(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP epsilonSEXP, SEXP methodSEXP, SEXP influence_measureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type influence_measure(influence_measureSEXP);
    rcpp_result_gen = Rcpp::wrap(CaseInfluence_logistic(X, Y, theta_0, t_max, lam, epsilon, method, influence_measure));
    return rcpp_result_gen;
END_RCPP
}
// LocalInfluence_logistic
arma::vec LocalInfluence_logistic(arma::mat X, arma::vec Y, arma::vec theta_0, double lam, std::string influence_measure);
RcppExport SEXP _Caseinflu_LocalInfluence_logistic(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP lamSEXP, SEXP influence_measureSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< std::string >::type influence_measure(influence_measureSEXP);
    rcpp_result_gen = Rcpp::wrap(LocalInfluence_logistic(X, Y, theta_0, lam, influence_measure));
    return rcpp_result_gen;
END_RCPP
}
// poisson_Newton_high_dimension
Rcpp::List poisson_Newton_high_dimension(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, int case_index, double epsilon, double L);
RcppExport SEXP _Caseinflu_poisson_Newton_high_dimension(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP case_indexSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_Newton_high_dimension(X, Y, theta_0, t_max, lam, case_index, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// poisson_Newton_low_dimension
Rcpp::List poisson_Newton_low_dimension(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, int case_index, double epsilon, double L);
RcppExport SEXP _Caseinflu_poisson_Newton_low_dimension(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP case_indexSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_Newton_low_dimension(X, Y, theta_0, t_max, lam, case_index, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// poisson_GD
Rcpp::List poisson_GD(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, int case_index, double epsilon, double L);
RcppExport SEXP _Caseinflu_poisson_GD(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP case_indexSEXP, SEXP epsilonSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_GD(X, Y, theta_0, t_max, lam, case_index, epsilon, L));
    return rcpp_result_gen;
END_RCPP
}
// poisson_compute_LOO
arma::vec poisson_compute_LOO(arma::mat X, arma::vec Y, arma::vec theta_init, double lam, int case_index);
RcppExport SEXP _Caseinflu_poisson_compute_LOO(SEXP XSEXP, SEXP YSEXP, SEXP theta_initSEXP, SEXP lamSEXP, SEXP case_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_init(theta_initSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< int >::type case_index(case_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_compute_LOO(X, Y, theta_init, lam, case_index));
    return rcpp_result_gen;
END_RCPP
}
// CaseInfluence_poisson
Rcpp::List CaseInfluence_poisson(arma::mat X, arma::vec Y, arma::vec theta_0, double t_max, double lam, double epsilon, std::string method);
RcppExport SEXP _Caseinflu_CaseInfluence_poisson(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP t_maxSEXP, SEXP lamSEXP, SEXP epsilonSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(CaseInfluence_poisson(X, Y, theta_0, t_max, lam, epsilon, method));
    return rcpp_result_gen;
END_RCPP
}
// LocalInfluence_poisson
arma::vec LocalInfluence_poisson(arma::mat X, arma::vec Y, arma::vec theta_0, double lam);
RcppExport SEXP _Caseinflu_LocalInfluence_poisson(SEXP XSEXP, SEXP YSEXP, SEXP theta_0SEXP, SEXP lamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta_0(theta_0SEXP);
    Rcpp::traits::input_parameter< double >::type lam(lamSEXP);
    rcpp_result_gen = Rcpp::wrap(LocalInfluence_poisson(X, Y, theta_0, lam));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Caseinflu_case_path_nonsmooth", (DL_FUNC) &_Caseinflu_case_path_nonsmooth, 10},
    {"_Caseinflu_CaseInfluence_nonsmooth", (DL_FUNC) &_Caseinflu_CaseInfluence_nonsmooth, 11},
    {"_Caseinflu_LocalInfluence_nonsmooth", (DL_FUNC) &_Caseinflu_LocalInfluence_nonsmooth, 11},
    {"_Caseinflu_rcpp_hello_world", (DL_FUNC) &_Caseinflu_rcpp_hello_world, 0},
    {"_Caseinflu_logistic_Newton_low_dimension", (DL_FUNC) &_Caseinflu_logistic_Newton_low_dimension, 8},
    {"_Caseinflu_logistic_Newton_high_dimension", (DL_FUNC) &_Caseinflu_logistic_Newton_high_dimension, 8},
    {"_Caseinflu_logistic_GD", (DL_FUNC) &_Caseinflu_logistic_GD, 8},
    {"_Caseinflu_logistic_compute_LOO", (DL_FUNC) &_Caseinflu_logistic_compute_LOO, 5},
    {"_Caseinflu_CaseInfluence_logistic", (DL_FUNC) &_Caseinflu_CaseInfluence_logistic, 8},
    {"_Caseinflu_LocalInfluence_logistic", (DL_FUNC) &_Caseinflu_LocalInfluence_logistic, 5},
    {"_Caseinflu_poisson_Newton_high_dimension", (DL_FUNC) &_Caseinflu_poisson_Newton_high_dimension, 8},
    {"_Caseinflu_poisson_Newton_low_dimension", (DL_FUNC) &_Caseinflu_poisson_Newton_low_dimension, 8},
    {"_Caseinflu_poisson_GD", (DL_FUNC) &_Caseinflu_poisson_GD, 8},
    {"_Caseinflu_poisson_compute_LOO", (DL_FUNC) &_Caseinflu_poisson_compute_LOO, 5},
    {"_Caseinflu_CaseInfluence_poisson", (DL_FUNC) &_Caseinflu_CaseInfluence_poisson, 7},
    {"_Caseinflu_LocalInfluence_poisson", (DL_FUNC) &_Caseinflu_LocalInfluence_poisson, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Caseinflu(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
